matrix:
  include:
    - language: python
      python: 3.4
      packages:
        - mediainfo
      install:
        - pip install -r opencv_iav/requirements.txt
        - pip install -r opencv_iav/test_requirements.txt
        - pip install coveralls
      script:
        - python -m unittest discover
      after_success:
        - coveralls --root ./opencv_iav

notifications:
  email: false
